# Generated by Django 5.2.4 on 2025-08-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='new_Student',
        ),
    ]
